"""requirements + agent_runs tables

Revision ID: 0006
Revises: 0005
Create Date: 2026-05-05 00:50:00

Week 3 — BRD→FRD synthesis. ``requirements`` holds individual FRD items
generated by the agent; ``agent_runs`` tracks every agent invocation with
typed status transitions.

Both tables CASCADE on project delete. ``source_document_id`` on
requirements uses ``ON DELETE SET NULL`` so deleting a BRD doesn't wipe
historical FRDs that were synthesized from it (they just lose source
attribution). Same for ``agent_runs.plan_id`` — runs survive plan deletion.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: Union[str, None] = "0005"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_document_id", sa.Integer(), nullable=True),
        sa.Column("source_chunk_ids", sa.JSON(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default="proposed",
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("embedding_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"], ["documents.id"], ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "kind IN ('FRD')",
            name="requirement_kind_valid",
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'edited', 'approved', 'rejected')",
            name="requirement_status_valid",
        ),
    )
    op.create_index(
        "ix_requirements_project_id", "requirements", ["project_id"],
    )
    op.create_index(
        "ix_requirements_project_code",
        "requirements",
        ["project_id", "code"],
        unique=True,
    )

    op.create_table(
        "agent_runs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            server_default="queued",
        ),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("output_summary_json", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["test_plans.id"], ondelete="SET NULL",
        ),
        sa.CheckConstraint(
            "kind IN ('brd_to_frd', 'frd_to_tc', 'execute', 'reporter')",
            name="agent_run_kind_valid",
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'paused', 'completed', "
            "'failed', 'cancelled')",
            name="agent_run_status_valid",
        ),
    )
    op.create_index("ix_agent_runs_project_id", "agent_runs", ["project_id"])


def downgrade() -> None:
    op.drop_index("ix_agent_runs_project_id", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(
        "ix_requirements_project_code", table_name="requirements",
    )
    op.drop_index(
        "ix_requirements_project_id", table_name="requirements",
    )
    op.drop_table("requirements")
